name: energysales-dev

services:
  postgres_dev:
    image: postgres:16.2-alpine3.19
    container_name: postgres_dev
    environment:
      POSTGRES_DB: ${DB_DEV_NAME}
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}
      PGPORT: ${DB_DEV_PORT}
    ports:
      - "5433:5433"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_DEV_USER} -d ${DB_DEV_NAME}"
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

volumes:
  postgres_dev_data:
