name: energysales

services:
  ktor_service:
    build:
      context: ./
      dockerfile: ./src/energysales-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - path: ./.env
  
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
