name: energysales-test

services:
  postgres_testing:
    image: postgres:16.2-alpine3.19
    container_name: postgres_testing
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_TESTING_NAME}
      POSTGRES_USER: ${DB_TESTING_USER}
      POSTGRES_PASSWORD: ${DB_TESTING_PASSWORD}
      PGPORT: ${DB_TESTING_PORT}
    ports:
      - "5434:5434"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_TESTING_USER} -d ${DB_TESTING_NAME}"
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

volumes:
  postgres_production_data:
