name: energysales-dev

services:
  ktor_service:
    build:
      context: ./
      dockerfile: ./src/energysales-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres_dev:
        condition: service_healthy
    environment:
      SERVER_PORT: ${SERVER_PORT}
      KTOR_DEV_MODE: true
      DB_HOST: ${DB_DEV_HOST}
      DB_PORT: ${DB_DEV_PORT}
      DB_NAME: ${DB_DEV_NAME}
      DB_USER: ${DB_DEV_USER}
      DB_PASSWORD: ${DB_DEV_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  
  postgres_dev:
    image: postgres:16.2-alpine3.19
    container_name: postgres_dev
    environment:
      POSTGRES_DB: ${DB_DEV_NAME}
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}
      PGPORT: ${DB_DEV_PORT}
    expose:
      - ${DB_DEV_PORT}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_DEV_USER} -d ${DB_DEV_NAME}"
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

volumes:
  postgres_dev_data:
